### ISSUE TITLE
Internal PHP functions are aliased

### ISSUE THREAD

**Issue by polevaultweb** [humbug/php-scoper#367] opened 2020-01-10 14:12 UTC
I have a couple of questions about the best practices around `whitelist-global-functions`

I'm scoping dependencies for a WordPress plugin, and found if `whitelist-global-functions` is set to true, then `/scoper-autoload.php` contains the aliases for functions in the global namespace (that are being used in my dependencies). However, some of these are native PHP functions, eg:

```
if (!function_exists('pcntl_signal')) {
    function pcntl_signal() {
        return \MY_PREFIX\pcntl_signal(...func_get_args());
    }
}
```

1) Why would native PHP functions need to be aliased? 

There are some other functions declared in my dependencies that are declared in the global namespace, and then correctly prefixed by PHP-Scoper, but then are aliased in the `/scoper-autoload.php`.

2) Do these functions need to be aliased? My dependencies will be calling the prefixed function, so do I care about other code outside of my plugin using the global namespace function?

In my use case, should I just turn `whitelist-global-functions` off? Appreciate your help @theofidry  :)

**Comment by theofidry** [comment] 2020-01-10 14:56
That's a good question. I don't remember all the details but it was for the Symfony VarDumper & Laravel helpers. I'm not sure anymore what the problem was that forced me to turn it on by default. But I problem ran into some issues and I shrugged it off: I don't consider registering stuff in the global namespace a good practice and don't think it's that common either.

So I probably ended up turning it on by default to cut short on those problems assuming that the issues encountered by conflicts there would be very unlikely.

Now that being said:

>Why would native PHP functions need to be aliased?

They should not: an internal symbol (function, class or constant) should _not_ be prefixed. So this is definitely a bug and probably has to do with the phpstorm stubs used

**Comment by polevaultweb** [comment] 2020-01-10 15:10
> I don't consider registering stuff in the global namespace a good practice and don't think it's that common either.

Thanks, I think that confirms my assumption i should disable `whitelist-global-functions` in my scoper config. Cheers @theofidry 

For the aliasing of native PHP functions, see the `367` branch of https://github.com/polevaultweb/php-scoper-phar-issue/tree/367 for reproducing 👍

**Comment by theofidry** [comment] 2020-01-22 17:51
@polevaultweb the `src` directory is missing in the reproducer and if I just try with:

```php
<?php

declare(strict_types=1);

namespace Acme;

final class Foo
{
    public function __invoke()
    {
        pcntl_signal_dispatch();
    }
}

```

it will work fine, so I'm really curious about that one!

**Comment by vielhuber** [comment] 2020-02-05 21:56
I realized a similiar case:

In my original code I have
```
$dom = new \DOMDocument();
/* ... */
$xpath = new \DOMXpath($dom);
```

php-scoper now scopes the second internal function falsly:
```
$dom = new \DOMDocument();
/* ... */
$xpath = new \_PhpScoper510df8cbaa13\DOMXpath($dom);
```

Now new \_PhpScoper510df8cbaa13\DOMXpath($dom); fails.
How do I get php-scoper to ignore also the second statement?

**Comment by theofidry** [comment] 2020-02-05 22:34
Sounds weird: it should be an internal symbol so it’s a legit bug.
Nonetheless you can get around it with a patcher (cf the doc)

**Comment by vielhuber** [comment] 2020-02-06 22:19
I've managed to get it working with an additional patcher:

```php
    'patchers' => [
        function (string $filePath, string $prefix, string $content): string {
            if (strpos($filePath,'path/to/file.php') !== false) {
                $content = str_replace('\\'.$prefix.'\\DOMXpath', '\\DOMXpath', $content);
            }
            return $content;
        }
    ]
```

**Comment by theofidry** [comment] 2020-02-10 09:13
@vielhuber @polevaultweb do you have any reproducer? I would be _very_ interested in one; just make sure before though that PHP-Scoper is up to date: it ships a list of stubs so if the PHAR is outdated then so is the stubs hence the list of known PHP core symbols

**Comment by vielhuber** [comment] 2020-02-10 09:33
Input:
```
<?php
$dom = new \DOMDocument();
$xpath = new \DOMXpath($dom);
```

Output:
```
<?php
namespace _PhpScoperb153fdd14e16;
$dom = new \DOMDocument();
$xpath = new \_PhpScoperb153fdd14e16\DOMXpath($dom);
```

Version: 0.13.1

Command: php php-scoper.phar add-prefix --no-config

**Comment by villfa** [comment] 2020-07-12 09:30
> Input:
> 
> ```
> <?php
> $dom = new \DOMDocument();
> $xpath = new \DOMXpath($dom);
> ```
> 
> Output:
> 
> ```
> <?php
> namespace _PhpScoperb153fdd14e16;
> $dom = new \DOMDocument();
> $xpath = new \_PhpScoperb153fdd14e16\DOMXpath($dom);
> ```
> 
> Version: 0.13.1
> 
> Command: php php-scoper.phar add-prefix --no-config

@vielhuber your problem here is that you wrote `DOMXpath` instead of [`DOMXPath`](https://www.php.net/manual/en/class.domxpath.php) (with a capital P).
This specific problem is related to #393.

**Comment by vielhuber** [comment] 2020-07-12 20:50
Thanks in advance!

**Comment by theofidry** [comment] 2020-09-05 12:12
I'll be closing this one as a duplicate of #393

**Closed by theofidry** 2020-09-05 12:12 UTC
Labels: critical bug
