### ISSUE TITLE
Exit code is zero when scoping a given file fails

### ISSUE THREAD

**Issue by padraic** [humbug/php-scoper#22] opened 2017-05-28 13:48 UTC
Noticed when going through tests, that one checks the exit code is 0 in the event of a file not existing. Last test in `AddPrefixCommandHandlerTest`.

**Comment by theofidry** [comment] 2017-06-04 16:42
Duplicate of https://github.com/humbug/php-scoper/issues/25, this is due to the fact that now an invalid file is skipped instead of being considered as an error.

**Closed by theofidry** 2017-06-04 16:42 UTC
