### ISSUE TITLE
Version 0.5.1 PHAR run fails on version contstraints exception

### ISSUE THREAD

**Issue by TomasVotruba** [humbug/php-scoper#150] opened 2018-02-15 08:28 UTC
### Steps to Reproduce

```bash
wget https://github.com/humbug/php-scoper/releases/download/0.5.1/php-scoper.phar
mv php-scoper.phar php-scoper 

wget https://github.com/humbug/php-scoper/releases/download/0.5.1/php-scoper.phar.pubkey
mv php-scoper.phar.pubkey php-scoper.pubkey

php-scoper
```

### Exception

```
PHP Fatal error:  Uncaught UnexpectedValueException: Invalid version string "7.1.11-0ubuntu0.17.10.1" in phar:///usr/local/bin/php-scoper/vendor/composer/semver/src/VersionParser.php:147
Stack trace:
#0 phar:///usr/local/bin/php-scoper/vendor/composer/semver/src/Semver.php(34): PhpScoper5a3e983ccd43c\Composer\Semver\VersionParser->normalize('7.1.11-0ubuntu0...')
#1 phar:///usr/local/bin/php-scoper/src/Autoload/Requirements.php(37): PhpScoper5a3e983ccd43c\Composer\Semver\Semver::satisfies('7.1.11-0ubuntu0...', '^7.1')
#2 phar:///usr/local/bin/php-scoper/src/Autoload/Requirements.php(25): PhpScoper5a3e983ccd43c\Humbug\PhpScoper\Autoload\Requirements->addPhpVersionRequirement(Array)
#3 phar:///usr/local/bin/php-scoper/src/check.php(28): PhpScoper5a3e983ccd43c\Humbug\PhpScoper\Autoload\Requirements->__construct('phar:///usr/loc...')
#4 phar:///usr/local/bin/php-scoper/bin/php-scoper(51): PhpScoper5a3e983ccd43c\Humbug\PhpScoper\check_requirements('phar:///usr/loc...', false)
#5 /usr/local/bin/php-scoper(10): require('phar:///usr/lo in phar:///usr/local/bin/php-scoper/vendor/composer/semver/src/VersionParser.php on line 147

**Comment by theofidry** [comment] 2018-02-15 08:38
Might be a duplicate of https://github.com/humbug/php-scoper/pull/141.

I can merge the patch but I'm a bit uneasy to do so without a test to prevent any regression :/

**Comment by TomasVotruba** [comment] 2018-02-15 08:47
How can merging PR with fix make broken PHAR worse?

**Comment by theofidry** [comment] 2018-02-15 09:46
It's not about making it worse, but about to make sure I'm not gonna break it again in a refactor or something

**Comment by TomasVotruba** [comment] 2018-02-15 09:55
Better done than perfect

**Comment by theofidry** [comment] 2018-02-15 10:02
Even if I merge it now it's not gonna be effective before the next tag release. And because there's a couple of BC/issues on master, I don't want to tag it before I'm done with the changes introduced by #117 which should make it significantly better.

So if the PR is not updated by then, I'll try to find a way to add the tests to include it to the release, but meanwhile it's not urgent.

Also #117 is gonna happen soon now I hope :) It's my next blocking issue for https://github.com/humbug/box/pull/31 and after the php-scoper integration to box I'm gonna do an alpha release of box.

**Closed** 2018-02-16 01:21 UTC
