### ISSUE TITLE
"use" Composer shouldn't be prefixed

### ISSUE THREAD

**Issue by kkmuffme** [humbug/php-scoper#1043] opened 2024-06-11 11:06 UTC
## Bug report

| Question    | Answer
| ------------| ---------------
| PHP-Scoper version | 0.18.11
| PHP version | 8.3.x
| Platform with version | Centos

```
use Composer\Script\Event;
```

should not be prefixed to

```
use My_Prefix\Composer\Script\Event;
```

since the composer classes are global and not prefixed.
Otherwise, this breaks composer scripts/requires scoper config patcher to "revert" this to non-namespaced.

**Comment by theofidry** [comment] 2024-06-11 13:03
I think that is the responsibility of the user. Not all Composer classes need to be exposed, for example `InstalledVersions` should be prefixed.

**Comment by theofidry** [comment] 2024-06-11 13:42
Ok sorry but I feel like this issue is missing quite some context.


```php
use Composer\Script\Event;
```

should not be prefixed to

```php
use My_Prefix\Composer\Script\Event;
```

As per my previous reply, it should in the sense that PHP-Scoper will not treat Composer's symbols differently. So by "I think that is the responsibility of the user." I mean that if you want some of them to not be scoped, it is your responsibility to configure it as such, as it would be wrong for PHP-Scoper to natively know if it should or not.

>My scoper config has all expose set to false/empty array

I struggle a bit to understand what you mean. Exposing a symbol does not prevent it from being prefixed, it means the non-prefixed version will still work. There is more details explanations with examples here:

- [for classes](https://github.com/humbug/php-scoper/blob/main/docs/configuration.md#exposing-classes)[
- [for functions](https://github.com/humbug/php-scoper/blob/main/docs/configuration.md#exposing-functions)

But in this case if you mean your project hooks onto Composer, e.g. for a Composer plugin, then you likely need to _exclude_, rather than _expose_, the Composer API. See [How to deal with unknown third-party symbols](
https://github.com/humbug/php-scoper/blob/main/docs/further-reading.md#how-to-deal-with-unknown-third-party-symbols)

Note that the same way there is a Symfony, Laravel and WP support entry, I'm happy to add a Composer plugin one if you have info to provide on it.

**Comment by theofidry** [comment] 2024-06-11 20:17
>All classes that are derived from composer itself (things that come e.g. in the composer phar) should be excluded by default and not scoped since they can't be used prefixed

But PHP-Scoper cannot know that in advance. Maybe you are working on a project that ships its own Composer and do something with it and that shipped Composer needs to be scoped.

> e.g. if you add a composer script, it will obviously load the Event class from composer that is OUTSIDE of the scoped directory.

Yes, in which case in your codebase you need to mark the used Composer API as _excluded_, not exposed.

If it's not clear enough code samples with the config would help :)

**Comment by theofidry** [comment] 2024-06-12 13:32
>I think the initial confusion stemmed from that it's unclear why some Composer is prefixed, while others are not at first glance - but that seems due to the autoload dumping.

Yes it's a bit confusing: basically the autoloader itself is fine because the class is dumped with a unique ID, so by design it is already "scoped", albeit by a different mechanism.

>vendor/composer/InstalledVersions.php however is prefixed

Indeed! It is necessary so that you can access to the installed or the versions of the packages that were prefixed with it (so a scoped dependency Guzzle may be of a different version than your app one).

**Comment by theofidry** [comment] 2024-06-14 07:51
Yes, that is pretty much what the e2e 035 is about:

The setup:
- a _scoped_ project that has Guzzle5 and displays its version with `InstalledVersions`
- a project that uses Guzzle6 and displays its version with `InstalledVersions`
- the 2nd project autoloads the first project before loading its own code

The test scope both and execute it. The result:


```
Autoload Scoped code. <-- Loads the Guzzle5 project
5.3.4.0
Guzzle5 loaded.
Autoload code. <-- Loads the Guzzle6 project
The hashes are matching. <-- Something else about `$GLOBALS['__composer_autoload_files']`
6.5.8.0
Done.
```

**Comment by theofidry** [comment] 2024-06-15 13:01
There is not much more actionables for me so I'll close this.

If you run into a concrete problem please open a new issue with a reproducer I could work on

**Closed by theofidry** 2024-06-15 13:01 UTC
